### ISSUE TITLE
MFA not prompting

### ISSUE THREAD

**Issue by wayalex** [MicrosoftDocs/partner-center-sdk#47] opened 2019-12-09 11:55 UTC
When attempting to get the auth code at the following url: https://login.microsoftonline.com/common/oauth2/authorize?client_id=ClientID&response_mode=form_post&response_type=code%20id_token&scope=openid%20profile&nonce=1

My account isn't prompted for MFA, just email address and password. If I login to portal.office.com with the same account then MFA is prompted. Is this an issue with the account, or with the service principal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81757a-da98-492e-aa46-cd920709432e
* Version Independent ID: fbf50fa1-8698-5e30-483b-2408426d349d
* Content: [Enable secure application model - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#feedback)
* Content Source: [develop/enable-secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/enable-secure-app-model.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment] 2020-01-14 03:02
@wayalex there could be a number of resources for this behavior. The most common is that you are leveraging conditional access policies that require multi-factor authentication for Office 365 and not other systems. Another possibility would be that you are leveraging Security Defaults and that by design does not prompt for every login unless you are a member of the administrative roles available for Azure Active Directory. Fortunately there is a way you can make it prompt each time. Simply append `&amr=mfa` as a query string parameter. This will force the prompt for multi-factor authentication.

**Comment by JasonWHowell** [comment] 2020-03-27 05:28
@wayalex Thanks for the question. Isaiah recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason

**Closed by JasonWHowell** 2020-03-27 05:28 UTC
Labels: triaged
